### PR TITLE
Target Markdown

### PR DESCRIPTION
**Pull request by wlandau**
# Prework

* [x] I understand and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and the [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] I have already submitted a [discussion topic](https://github.com/ropensci/targets/discussions) or [issue](https://github.com/ropensci/targets/issues) to discuss my idea with the maintainer.

# Related GitHub issues and pull requests

* Ref: #469, #470

# Summary

Target Markdown is here! Get the best of both worlds: the readable narrative of literate programming, and the sophisticated dependency management and caching system of `targets`. For a walkthrough, create a new R Markdown document in RStudio from the "Target Markdown" template: https://rstudio.github.io/rstudio-extensions/rmarkdown_templates.html. Source: https://github.com/ropensci/targets/blob/target_markdown/inst/rmarkdown/templates/targets/skeleton/skeleton.Rmd. This template will soon become a chapter in http://books.ropensci.org/targets/. 

Thanks to @cderv, @nviets, @emilyriederer, @ijlyttle, @GShotwell, @gadenbuie, and @tomsing1 for the input. Special thanks to @cderv for answering my deluge of questions in #469 and https://community.rstudio.com/t/suppress-evaluation-of-knitr-chunk-options-in-custom-language-engine, helping me figure out what was and was not possible in `knitr`, and ultimately circling me back to a successful strategy.

### CODE REVIEW

**Comment by cderv** [comment]
Hi @wlandau ! Nice work and glad I could be of help. 

just a note: Chunk label could in theory work with any character but know that this is not advice in all case. For example, for **bookdown** referencing mechanism it must be a-z, A-Z, 0-9 and dash (`-`). So usually this is a recommandation to not use underscore (`_`). This concerns for now only **bookdown** usage and we do not enforce anything - user must take care label name. See note box in https://bookdown.org/yihui/bookdown/figures.html

I am not sure that this new way of working with **targets** can have issue with this, but if this is not so important to you, I would use `-` instead of `_` in chunk label name in your skeleton file.

**Comment by wlandau** [comment]
Thanks, @cderv. Just updated the labeling scheme.

**Comment by fkohrt** [comment]
@wlandau Using dashes as chunk labels in the [user manual section on Target Markdown](https://books.ropensci.org/targets/markdown.html#target-markdown) might confuse people, because from there it is only a small step to add `tar_simple = TRUE` and then trip over the assertion that target names should feel like variable names (see #679).

With [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/r-code.html) recommending to only use alphanumeric characters (`a-z`, `A-Z` and `0-9`) and dashes (`-`) for chunk labels and with `targets`' restrictions on target names which might be named after chunk labels, I believe it would be better to consistently use alphanumeric characters only and to use camel case instead of special separators ([periods are to be avoided as well](https://yihui.org/knitr/options/#chunk-options)).

**Comment by wlandau** [comment]
@fkohrt, I see what you are saying, but I strongly prefer to avoid camel case.

**Pull request merged**
