### PR TITLE
Update overview.Rmd

### PR DESCRIPTION
**Pull request by liutiming**
i have added how i would sell targets to my colleagues: focusing more on the user experience than the technical implementation. feel free to discard/adapt as needed

### CODE REVIEW

**Comment by liutiming** [comment]
since the technical details are explained well in the manual, the first paragraphs would better focus on "why" targets rather than "how" target works.

**Comment by wlandau** [comment]
Thanks, I like where you are going with this. How about something like "... accelerates analysis with easy-to-configure parallel computing, enhances reproducibility, and reduces the burdens of repeated computation and manual data micromanagement"?

**Comment by liutiming** [comment]
thanks. yup sounds better!

**Comment by wlandau** [comment]
Do you plan to update your PR, or should I write this directly in the vignette?

**Comment by liutiming** [comment]
just did that :)

**Review by wlandau — APPROVED** [review]

**Pull request merged**
