### PR TITLE
Azure storage

### PR DESCRIPTION
**Pull request by jeffery-leirness-noaa**
# Prework

* [x] I understand and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and the [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] I have already submitted a [discussion topic](https://github.com/ropensci/targets/discussions) or [issue](https://github.com/ropensci/targets/issues) to discuss my idea with the maintainer.

# Related GitHub issues and pull requests

* Ref: Discussion #1104

# Summary

Implements basic utility functions R/utils_azure.R and associated tests (tests/azure/test-utils_azure.R) to allow `targets` to interface with Azure storage.

### CODE REVIEW

**Comment by wlandau** [comment]
Thanks for putting this together, @jeffery-leirness-noaa. At the same time you worked on this PR, I implemented customizable content-addressable storage in #1322. Would you check it out and let me know if `tar_repository_cas()` is enough for you to use Azure storage with `targets`? If it works for you and Azure storage integration can exist outside the `targets` package itself, this will reduce the maintenance load on my end.

**Comment by jeffery-leirness-noaa** [comment]
Hi @wlandau. I've been testing the functionality of `tar_repository_cas()` and I think it's a wonderfully elegant solution! So far, I've tested {targets} workflows using both Google Drive and Azure Storage as the specified repository for CAS with (mostly) success. Thank you for this brilliant integration!

I am encountering an error where `tar_read()` fails when utilizing `tar_option_set()` to specify the custom repository and resources (via `tar_resources(repository_cas = tar_resources_repository_cas(envvars = c()))`. `tar_make()` works successfully without issue, but `tar_read()` fails unless the `tar_option_set()` code block is run explicitly prior to `tar_read()`. Hopefully that makes sense. If not, please let me know and I can elaborate further or attempt to provide a reproducible example.

**Comment by PatrickCoyle** [comment]
@jeffery-leirness-noaa , thank you for working on this topic. Is there an example of using `tar_repository_cas()` for Azure storage that you could share? This would very useful!

**Comment by jeffery-leirness-noaa** [comment]
Hi @PatrickCoyle. I meant to provide an example sooner, but other priorities shifted my focus so thank you for the reminder and suggestion.

Here's a minimal example `_targets.R` file that sets the necessary options for `targets` to work with Azure.

```r
# source R scripts in the R/ folder
targets::tar_source()

# set target options
token <- azure_auth_token()
token$refresh()
targets::tar_option_set(
  repository = targets::tar_repository_cas(upload = azure_upload,
                                           download = azure_download,
                                           exists = azure_exists),
  resources = targets::tar_resources(
    repository_cas = targets::tar_resources_repository_cas(
      envvars = c(TARGETS_AUTH_TOKEN = token$credentials$access_token)
    ))
)
```

The R functions `azure_auth_token`, `azure_upload`, `azure_download`, and `azure_exists` are defined in a second file saved within the project-level R/ directory:

```r
# unless defined within each azure_upload(), azure_download(), and 
# azure_exists() function, azure_auth_token() is not accessible from the other 
# utility functions, which can lead to an issue when a token expires while a 
# target is running. A possible solution is to put the azure_auth_token() 
# function into a separate R package that can be installed via github and 
# referenced via <package-name>::azure_auth_token().
azure_auth_token <- function(
    resource = "https://storage.azure.com",
    tenant = "common",
    app = NULL,
    auth_type = "device_code"
) {
  tryCatch(
    AzureAuth::get_managed_token(resource),
    error = function(err) {
      if (is.null(app)) {
        app <- try(AzureRMR::get_azure_login()$token$client$client_id,
                   silent = TRUE)
        if (inherits(app, "try-error")) {
          AzureRMR::create_azure_login()
          app <- AzureRMR::get_azure_login()$token$client$client_id
        }
      }
      tokens <- AzureRMR::list_azure_tokens()
      resources <- purrr::map(tokens, \(x) x$resource)
      token_use <- match(resource, resources)[1]
      if (!is.na(token_use)) {
        tokens[[token_use]]
      } else {
        AzureRMR::get_azure_token(resource,
                                  tenant = tenant,
                                  app = app,
                                  auth_type = auth_type)
      }
    }
  )
}

azure_upload <- function(key, path) {
  if (fs::is_dir(path)) {
    stop("This CAS repository does not support directory outputs.")
  }
  azure_auth_token <- function(
    resource = "https://storage.azure.com",
    tenant = "common",
    app = NULL,
    auth_type = "device_code"
  ) {
    tryCatch(
      AzureAuth::get_managed_token(resource),
      error = function(err) {
        if (is.null(app)) {
          app <- try(AzureRMR::get_azure_login()$token$client$client_id,
                     silent = TRUE)
          if (inherits(app, "try-error")) {
            AzureRMR::create_azure_login()
            app <- AzureRMR::get_azure_login()$token$client$client_id
          }
        }
        tokens <- AzureRMR::list_azure_tokens()
        resources <- purrr::map(tokens, \(x) x$resource)
        token_use <- match(resource, resources)[1]
        if (!is.na(token_use)) {
          tokens[[token_use]]
        } else {
          AzureRMR::get_azure_token(resource,
                                    tenant = tenant,
                                    app = app,
                                    auth_type = auth_type)
        }
      }
    )
  }
  AzureStor::upload_to_url(path,
                           dest = paste(Sys.getenv("TARGETS_ENDPOINT"),
                                        Sys.getenv("TARGETS_CONTAINER"),
                                        targets::tar_path_store(), key, sep = "/"),
                           token = azure_auth_token())
}

azure_download <- function(key, path) {
  azure_auth_token <- function(
    resource = "https://storage.azure.com",
    tenant = "common",
    app = NULL,
    auth_type = "device_code"
  ) {
    tryCatch(
      AzureAuth::get_managed_token(resource),
      error = function(err) {
        if (is.null(app)) {
          app <- try(AzureRMR::get_azure_login()$token$client$client_id,
                     silent = TRUE)
          if (inherits(app, "try-error")) {
            AzureRMR::create_azure_login()
            app <- AzureRMR::get_azure_login()$token$client$client_id
          }
        }
        tokens <- AzureRMR::list_azure_tokens()
        resources <- purrr::map(tokens, \(x) x$resource)
        token_use <- match(resource, resources)[1]
        if (!is.na(token_use)) {
          tokens[[token_use]]
        } else {
          AzureRMR::get_azure_token(resource,
                                    tenant = tenant,
                                    app = app,
                                    auth_type = auth_type)
        }
      }
    )
  }
  AzureStor::download_from_url(paste(Sys.getenv("TARGETS_ENDPOINT"),
                                     Sys.getenv("TARGETS_CONTAINER"),
                                     targets::tar_path_store(), key, sep = "/"),
                               dest = path,
                               token = azure_auth_token(),
                               overwrite = TRUE)
}

azure_exists <- function(key) {
  azure_auth_token <- function(
    resource = "https://storage.azure.com",
    tenant = "common",
    app = NULL,
    auth_type = "device_code"
  ) {
    tryCatch(
      AzureAuth::get_managed_token(resource),
      error = function(err) {
        if (is.null(app)) {
          app <- try(AzureRMR::get_azure_login()$token$client$client_id,
                     silent = TRUE)
          if (inherits(app, "try-error")) {
            AzureRMR::create_azure_login()
            app <- AzureRMR::get_azure_login()$token$client$client_id
          }
        }
        tokens <- AzureRMR::list_azure_tokens()
        resources <- purrr::map(tokens, \(x) x$resource)
        token_use <- match(resource, resources)[1]
        if (!is.na(token_use)) {
          tokens[[token_use]]
        } else {
          AzureRMR::get_azure_token(resource,
                                    tenant = tenant,
                                    app = app,
                                    auth_type = auth_type)
        }
      }
    )
  }
  AzureStor::storage_endpoint(Sys.getenv("TARGETS_ENDPOINT"),
                              token = azure_auth_token()) |>
    AzureStor::storage_container(name = Sys.getenv("TARGETS_CONTAINER")) |>
    AzureStor::storage_file_exists(fs::path(targets::tar_path_store(), key))
}
```

The tricky part is that each Azure utility function needs to be fully self-contained, which creates a challenge when authentication is required. My solution (above) to simply place the azure_auth_token() function inside each of the other Azure utility functions is not especially elegant, but it works. Also, the azure_auth_token() function itself has not been tested extensively and may need modification based on your particular Azure setup; although, I did test it using both my local machine and within a custom Azure compute instance and was able to successfully obtain an authentication token. Having some familiarity with the `AzureAuth` and/or `AzureRMR` packages will help.

The only other setup required is to specify the `TARGETS_ENDPOINT` and `TARGETS_CONTAINER` environment variables, which I did within a project-level `.Renviron` file:

```r
# for blob storage
TARGETS_ENDPOINT="https://<storage-account-name>.blob.core.windows.net"
TARGETS_CONTAINER="<blob-container-name>"
```

The `AzureStor` package functions are useful for reading/writing data directly from/to Azure storage if that is needed. If you have any questions or any issues with this solution let me know and I can help troubleshoot. Cheers!

**Comment by wlandau** [comment]
> The tricky part is that each Azure utility function needs to be fully self-contained, which creates a challenge when authentication is required. My solution (above) to simply place the azure_auth_token() function inside each of the other Azure utility functions is not especially elegant, but it works. 

If you put those functions in a custom R package, then you won't need to vendor `azure_auth_token()` inside the other functions. Also, it will save space in `_targets/meta/meta` because the `tar_repository_cas()` output string will be much shorter.

> The only other setup required is to specify the TARGETS_ENDPOINT and TARGETS_CONTAINER environment variables, which I did within a project-level .Renviron file:

That's a good workaround. You could alternatively set those envvars in `tar_resources_repository_cas()`.

**Comment by wlandau** [comment]
Closing the PR since we have aligned on a solution based on `tar_repository_cas()`, but please feel free to open a new [discussion thread](https://github.com/ropensci/targets/discussions) to continue the conversation.

**Pull request closed without merging**
